# Spring Cloud Dataflow Server for Apache Mesos image:https://travis-ci.org/trustedchoice/spring-cloud-dataflow-server-mesos.svg?branch=master[Build Status, link=https://travis-ci.org/trustedchoice/spring-cloud-dataflow-server-mesos] image:https://img.shields.io/maven-central/v/com.trustedchoice/spring-cloud-deployer-mesos.svg[Maven Central] image:https://img.shields.io/gitter/room/spring-cloud/spring-cloud-dataflow.svg[Gitter, link=https://gitter.im/spring-cloud/spring-cloud-dataflow]

This project provides support for deploying https://github.com/spring-cloud/spring-cloud-dataflow[Spring Cloud Data Flow]'s streaming data pipelines to Apache Mesos using Marathon and Chronos. It includes an implementation of Spring Cloud Data Flow’s https://github.com/spring-cloud/spring-cloud-deployer[Deployer SPI] using Marathon for stream apps and Chronos for task apps.

Please refer to the http://docs.spring.io/spring-cloud-dataflow-server-mesos/docs/current-SNAPSHOT/reference/htmlsingle/#_deploying_streams_and_tasks_on_mesos_and_marathon_chronos[reference documentation] on how to get started.

=== Contributing

We love contributions.  Follow this http://docs.spring.io/spring-cloud-dataflow-server-mesos/docs/current-SNAPSHOT/reference/htmlsingle/#contributing[link] for more information on how to contribute.

=== Building

Clone the repo and type 

----
$ ./mvnw clean install 
----

To build the docker image for the Data Flow Server

----
$ ./mvnw package docker:build -pl :spring-cloud-dataflow-server-mesos
----

For more information on building, see this http://docs.spring.io/spring-cloud-dataflow-server-mesos/docs/current-SNAPSHOT/reference/htmlsingle/#building[link].

=== Trademarks and licenses
The source code of TrustedChoice's Spring Cloud Dataflow Server for Apache Mesos is licensed under [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0)

Spring, Spring Boot and Spring Cloud are trademarks of [Pivotal Software, Inc.](https://pivotal.io/) in the U.S. and other countries.

Apache Mesos, the Apache feather logo, and the Apache Mesos project logo are trademarks of [The Apache Software Foundation](https://apache.org/).